name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.1
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
    - .env
